services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: 'dms'
        image: dms:1.0.0
        ports:
            - "8092:8080"
        restart: unless-stopped
        environment:
            APP_NAME: 'Jcara Backup Library'
            APP_ENV: local
            APP_KEY: ${APP_KEY:-base64:LVjlDrCIP0TG3FqUQFWDNNe6fGF2CJKwVTTOwCi8coM=}
            APP_DEBUG: true
            APP_URL: http://localhost:8092
            APP_TIMEZONE: "Asia/Jakarta"
            SCOUT_DRIVER: database
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: db_dms
            DB_USERNAME: dev
            DB_PASSWORD: dev
            BROADCAST_DRIVER: log
            CACHE_DRIVER: file
            FILESYSTEM_DISK: local
            QUEUE_CONNECTION: sync
            SESSION_DRIVER: file
            SESSION_LIFETIME: 120
            SESSION_SECURE_COOKIE: false
            SESSION_HTTP_ONLY: true
            SESSION_SAME_SITE: strict
            TZ: 'Asia/Jakarta'
            DEBUGBAR_ENABLED: false
        volumes:
            - dms_logs:/var/www/html/storage/logs
            - dms_storage:/var/www/html/storage/app
            - dms_nginx_logs:/var/log/nginx
        depends_on:
            db:
                condition: service_healthy
        networks:
            - dms_network

    db:
        image: mysql:8.0
        container_name: dms-db
        environment:
            MYSQL_ROOT_PASSWORD: dms
            MYSQL_DATABASE: db_dms
            MYSQL_USER: dms
            MYSQL_PASSWORD: dms
            TZ: 'Asia/Jakarta'
        ports:
            - "3308:3306"
        volumes:
            - dms_db:/var/lib/mysql
            - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ./docker/init/mysql:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 60s
        restart: unless-stopped
        networks:
            - dms_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: dms-phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            TZ: 'Asia/Jakarta'
            UPLOAD_LIMIT: 128M
            MAX_EXECUTION_TIME: 3600
        depends_on:
            - db
        ports:
            - "8092:80"
        restart: unless-stopped
        networks:
            - dms_network

volumes:
    dms_db:
        name: "dms_db"
    dms_logs:
        name: "dms_logs"
    dms_storage:
        name: "dms_storage"
    dms_nginx_logs:
        name: "dms_nginx_logs"

networks:
    dms_network:
        name: "dms_network"
